using CEnum: @cenum

const NULL = C_NULL

# This file is automatically generated by Clang.jl. Don't edit it manually. If needed,
# look at the "generators/" directory and modify the relevant files there.
